#+title: VitisOmics
#+author: Timothée Flutre

# see https://github.com/timflutre/perso/blob/master/emacs
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \textwidth 16cm
#+latex_header: \oddsidemargin 0.5cm
#+latex_header: \evensidemargin 0.5cm

* Overview
This document contains the documentation for the "VitisOmics" project.
This project aims at handling "omics" data in the genus Vitis (e.g. grapevine) in an open and reproducible way.

Such data are available from various places, Genoscope, URGI, NCBI, EBI, etc, and [[http://www.vitaceae.org/index.php/Genome_Sequencing][several]] [[http://www.vitaceae.org/index.php/Annotation][committes]] from the IGGP (International Grape Genome Program) strive at improving interoperability.
But my attempt, via the usage of git and GitHub, could prove for the community to be a useful addition to these efforts.

The project directory is organized as advised by Noble ([[http://dx.doi.org/10.1371/journal.pcbi.1000424][PLoS Computational Biology 2009]]):

On any Unix-like system, it is easily done with the following commands:
#+begin_src sh
touch AUTHORS COPYING README; mkdir -p doc data src bin results
#+end_src

On any Unix-like system, it can also be easily compressed and transferred (ignoring large data files):
#+begin_src sh
cd ..; tar -czvf VitisOmics.tar.gz \
--exclude=VitisOmics/data --exclude=VitisOmics/results \
--exclude="*~" --exclude=".*" VitisOmics
#+end_src

** Contributors

As of today: Timothée Flutre, Charles Romieu, Gautier Sarah

* Data
#+begin_src sh
cd data/
#+end_src

TODO: retrieve genome data from other cultivars than PN40024, e.g. Sultanina and Tannat

** URGI
- https://urgi.versailles.inra.fr/Species/Vitis/Data-Sequences/Genome-sequences

#+begin_src sh
../../src/download_urgi.bash
#+end_src

When needed, the script decompresses zip files and compress them again but with gzip instead.

** NCBI
- http://www.ncbi.nlm.nih.gov/genome/401
- ftp://ftp.ncbi.nlm.nih.gov/genomes/Vitis_vinifera/

#+begin_src sh
../../src/download_ncbi.bash
#+end_src

Note the important file =scaffold_names= which provides the correspondence between original scaffold names (i.e. from the sequencing center) and various NCBI identifiers (RefSeq, GenBank, etc).

** EBI
12X.0 as well as soft-masking by RepeatMasker

#+begin_src sh
../../src/download_ebi.bash
#+end_src

* Results
#+begin_src sh
cd results/
#+end_src

On a computer cluster, indexed files could be copied for usage by everyone, e.g. in =/Genomics/Vitis= if on the CIRAD cluster of the [[http://southgreen.fr/][SouthGreen]] platform.

One needs to keep the info about the source (URGI or NCBI) because differences in terms of N spacers and additional scaffolds (from Aegilops) at the NCBI.

** URGI
#+begin_src sh
cd urgi/
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_chroms_URGI=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/VV_chr12x.fsa.gz .
echo "../../src/reformat_VV_chr12x.bash" \
  | qsub -cwd -j y -V -N reformat_VV_chr12x -q bioinfo.q
#+end_src

Check:
#+begin_src sh
zcat VV_chr12x.fsa.gz | wc -l # 8240706
zcat VV_chr12x.fsa.gz | grep -c ">" # 33
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | wc -l # 8240706
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | grep -c ">" # 33
diff <(zcat VV_chr12x.fsa.gz) <(zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | md5sum # eff315994fafe35333462b9595e10ce5
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_scaffolds_EMBL_r102=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/VV_12X_embl_102_Scaffolds.fsa.gz .
echo "../../src/reformat_VV_12X_embl_102_Scaffolds.bash" \
  | qsub -cwd -j y -V -N reformat_VV_12X_embl_102_Scaffolds -q bioinfo.q
#+end_src

Check:
#+begin_src sh
zcat VV_12X_embl_102_Scaffolds.fsa.gz | wc -l # 8091565
zcat VV_12X_embl_102_Scaffolds.fsa.gz | grep -c ">" # 2059
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | wc -l # 8091565
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | grep -c ">" # 2059
diff <(zcat VV_12X_embl_102_Scaffolds.fsa.gz) <(zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | md5sum # 4fa2432d7a66c019c7cb41ee4d0cb7bc
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_contigs_EMBL_r102=
TODO

*** Reformat sequence headers for =VITVI_PN40024_12x_v2_chroms_URGI=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/12Xv2_grapevine_genome_assembly.fa.gz .
echo "../../src/reformat_12Xv2_grapevine_genome_assembly.bash" \
  | qsub -cwd -j y -V -N reformat_12Xv2_grapevine_genome_assembly -q bioinfo.q
#+end_src

Check:
#+begin_src sh
zcat 12Xv2_grapevine_genome_assembly.fa.gz | wc -l # 8103449
zcat 12Xv2_grapevine_genome_assembly.fa.gz | grep -c ">" # 20
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | wc -l # 8103449
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | grep -c ">" # 20
diff <(zcat 12Xv2_grapevine_genome_assembly.fa.gz) <(zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | md5sum # 4e487c28eaf19ef59b0b6128b73935af
#+end_src

*** Format =VITVI_PN40024_12x_v0_chroms_URGI= for BLASTn
TODO: change Vvin to VITVI
#+begin_src sh
../../src/format_Vvin-PN40024-12x-chr_blastn.bash
#+end_src

*** Index =VITVI_PN40024_12x_v0_chroms_URGI= for BWA
Launch:
#+begin_src sh
echo "../../src/bwa_index_VITVI_PN40024_12x_v0_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bwa_index_VITVI_PN40024_12x_v0_chroms_URGI -q bioinfo.q
#+end_src

*** Index =VITVI_PN40024_12x_v2_chroms_URGI= for BWA
Launch:
#+begin_src sh
echo "../../src/bwa_index_VITVI_PN40024_12x_v2_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bwa_index_VITVI_PN40024_12x_v2_chroms_URGI -q bioinfo.q
#+end_src
