#+title: VitisOmics
#+author: Timothée Flutre

# see https://github.com/timflutre/perso/blob/master/emacs
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \textwidth 16cm
#+latex_header: \oddsidemargin 0.5cm
#+latex_header: \evensidemargin 0.5cm

* Overview
This document contains the documentation for the "VitisOmics" project.
This project aims at handling "omics" data in the genus Vitis (e.g. grapevine) in an open and reproducible way.

Such data are available from various places, Genoscope, URGI, NCBI, EBI, etc, and several committes from the IGGP (International Grape Genome Program) strive at improving interoperability.
But my attempt, via the usage of git and GitHub, could prove for the community to be a useful addition to these efforts.

The project directory is organized as advised by Noble ([[http://dx.doi.org/10.1371/journal.pcbi.1000424][PLoS Computational Biology 2009]]):

On any Unix-like system, it is easily done with the following commands:
#+begin_src sh
touch AUTHORS COPYING README; mkdir -p doc data src bin results
#+end_src

On any Unix-like system, it can also be easily compressed and transferred (ignoring large data files):
#+begin_src sh
cd ..; tar -czvf VitisOmics.tar.gz \
--exclude=VitisOmics/data --exclude=VitisOmics/results \
--exclude="*~" --exclude=".*" VitisOmics
#+end_src

* Data
#+begin_src sh
cd data/
#+end_src

TODO: retrieve genome data from other cultivars than PN40024, e.g. Sultanina and Tannat

** URGI
- https://urgi.versailles.inra.fr/Species/Vitis/Data-Sequences/Genome-sequences

#+begin_src sh
../../src/download_urgi.bash
#+end_src

When needed, the script decompresses zip files and compress them again but with gzip instead.

** NCBI
- http://www.ncbi.nlm.nih.gov/genome/401
- ftp://ftp.ncbi.nlm.nih.gov/genomes/Vitis_vinifera/

#+begin_src sh
../../src/download_ncbi.bash
#+end_src

** EBI
12X.0 as well as soft-masking by RepeatMasker

#+begin_src sh
../../src/download_ebi.bash
#+end_src

* Results
#+begin_src sh
cd results/
#+end_src

On a computer cluster, indexed files could be copied for usage by everyone, e.g. in =/Genomics/Vitis= if on the CIRAD cluster of the [[http://southgreen.fr/][SouthGreen]] platform.

TODO: use the 5-letter code VITVI to name files, as advised by Grimplet et al, 2014

** URGI
*** Reformat sequence headers of file =VV_chr12x.fsa.gz=
#+begin_src sh
../../src/reformat_VV_chr12x.bash # take some time
zcat VV_chr12x.fsa.gz | wc -l # 8240706
zcat Vvin-PN40024-12x-chr.fa.gz | wc -l # 8240706
diff <(zcat Vvin-PN40024-12x-chr.fa.gz) <(zcat VV_chr12x.fsa.gz)
#+end_src

*** Reformat sequence headers of file =VV_12X_embl_102_Scaffolds.fsa.gz=
so that they comply with =transpose_annotation=:
https://github.com/SouthGreenPlatform/utils/tree/master/transpose_annotation/

#+begin_src sh
../../src/reformat_VV_12X_embl_102_Scaffolds.bash # take some time
zcat VV_12X_embl_102_Scaffolds.fsa.gz | wc -l # 8091565
zcat Vvin-PN40024-12x-scaff.fa.gz | wc -l # 8091565
diff <(zcat Vvin-PN40024-12x-scaff.fa.gz) <(zcat VV_12X_embl_102_Scaffolds.fsa.gz)
#+end_src

*** Format Vvin-PN40024-12x-chr.fa.gz for BLASTn
#+begin_src sh
../../src/format_Vvin-PN40024-12x-chr_blastn.bash
#+end_src

*** Index Vvin-PN40024-12x-chr.fa.gz for BWA
#+begin_src sh
../../src/index_Vvin-PN40024-12x-chr_bwa.bash
#+end_src
