#+title: VitisOmics
#+author: Timothée Flutre

# see https://github.com/timflutre/perso/blob/master/emacs
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \textwidth 17cm
#+latex_header: \oddsidemargin 0.5cm
#+latex_header: \evensidemargin 0.5cm

* Overview
This document contains the documentation for the "VitisOmics" project.
This project aims at handling "omics" data in the genus Vitis (e.g. grapevine) in an open and reproducible way.

Such data are available from various places, Genoscope, URGI, NCBI, EBI, etc, and [[http://www.vitaceae.org/index.php/Genome_Sequencing][several]] [[http://www.vitaceae.org/index.php/Annotation][committes]] from the IGGP (International Grape Genome Program) strive at improving interoperability.
But my attempt, via the usage of [[http://www.git-scm.com/book/en/v2][git]] and GitHub, could prove for the community to be a useful addition to these efforts.

The project directory is organized as advised by Noble ([[http://dx.doi.org/10.1371/journal.pcbi.1000424][PLoS Computational Biology 2009]]):

On any Unix-like system, it is easily done with the following commands:
#+begin_src sh
touch AUTHORS COPYING README; mkdir -p doc data src bin results
#+end_src

On any Unix-like system, it can also be easily compressed and transferred (ignoring large data files):
#+begin_src sh
cd ..; tar -czvf VitisOmics.tar.gz \
--exclude=VitisOmics/data --exclude=VitisOmics/results \
--exclude="*~" --exclude=".*" VitisOmics
#+end_src

** Contributors

The person roles comply with R's guidelines (The R Journal Vol. 4/1, June 2012).

- Timothée Flutre (cre,aut)
- Gautier Sarah (ctb)

* Data
#+begin_src sh
cd data/
#+end_src

TODO: retrieve genome data from other cultivars than PN40024, e.g. Sultanina and Tannat

** URGI
- https://urgi.versailles.inra.fr/Species/Vitis/Data-Sequences/Genome-sequences

#+begin_src sh
../../src/download_urgi.bash
#+end_src

When needed, the script decompresses zip files and compress them again but with gzip instead.

** NCBI
- http://www.ncbi.nlm.nih.gov/genome/401
- ftp://ftp.ncbi.nlm.nih.gov/genomes/Vitis_vinifera/

#+begin_src sh
../../src/download_ncbi.bash
#+end_src

Note the important file =scaffold_names= which provides the correspondence between original scaffold names (i.e. from the sequencing center) and various NCBI identifiers (RefSeq, GenBank, etc).

** EBI
12X.0 as well as soft-masking by RepeatMasker

#+begin_src sh
../../src/download_ebi.bash
#+end_src

* Results
#+begin_src sh
cd results/
#+end_src

On a computer cluster, indexed files could be copied for usage by everyone, e.g. in =/Genomics/Vitis= if on the CIRAD cluster of the [[http://southgreen.fr/][SouthGreen]] platform.

One needs to keep the info about the source (URGI or NCBI) because differences in terms of N spacers and additional scaffolds (from Aegilops) at the NCBI.

TODO: compress fasta files with BGZIP instead of GZIP

** URGI
#+begin_src sh
cd urgi/
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_chroms_URGI=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/VV_chr12x.fsa.gz .
echo "../../src/reformat_VV_chr12x.bash" \
  | qsub -cwd -j y -V -N reformat_VV_chr12x -q normal.q
#+end_src

Check:
#+begin_src sh
zcat VV_chr12x.fsa.gz | wc -l # 8240706
zcat VV_chr12x.fsa.gz | grep -c ">" # 33
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | wc -l # 8240706
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | grep -c ">" # 33
diff <(zcat VV_chr12x.fsa.gz) <(zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v0_chroms_URGI.fa.gz | md5sum # eff315994fafe35333462b9595e10ce5
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_scaffolds_EMBL_r102=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/VV_12X_embl_102_Scaffolds.fsa.gz .
echo "../../src/reformat_VV_12X_embl_102_Scaffolds.bash" \
  | qsub -cwd -j y -V -N reformat_VV_12X_embl_102_Scaffolds -q normal.q
#+end_src

Check:
#+begin_src sh
zcat VV_12X_embl_102_Scaffolds.fsa.gz | wc -l # 8091565
zcat VV_12X_embl_102_Scaffolds.fsa.gz | grep -c ">" # 2059
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | wc -l # 8091565
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | grep -c ">" # 2059
diff <(zcat VV_12X_embl_102_Scaffolds.fsa.gz) <(zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v0_scaffolds_EMBL_r102.fa.gz | md5sum # 4fa2432d7a66c019c7cb41ee4d0cb7bc
#+end_src

*** Reformat sequence headers for =VITVI_PN40024_12x_v0_contigs_EMBL_r102=
TODO

*** Reformat sequence headers for =VITVI_PN40024_12x_v2_chroms_URGI=
Launch script:
#+begin_src sh
ln -s ../../data/urgi/12Xv2_grapevine_genome_assembly.fa.gz .
echo "../../src/reformat_12Xv2_grapevine_genome_assembly.bash" \
  | qsub -cwd -j y -V -N reformat_12Xv2_grapevine_genome_assembly -q normal.q
#+end_src

Check:
#+begin_src sh
zcat 12Xv2_grapevine_genome_assembly.fa.gz | wc -l # 8103449
zcat 12Xv2_grapevine_genome_assembly.fa.gz | grep -c ">" # 20
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | wc -l # 8103449
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | grep -c ">" # 20
diff <(zcat 12Xv2_grapevine_genome_assembly.fa.gz) <(zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz)
#+end_src

Only the headers differ, not the sequences, so everything is fine.

Basic stats:
#+begin_src sh
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz | md5sum # 4e487c28eaf19ef59b0b6128b73935af
#+end_src

Length of each sequence:
#+begin_src sh
zcat VITVI_PN40024_12x_v2_chroms_URGI.fa.gz \
  | awk 'BEGIN{RS=">"} {split($0,a,"\n"); 
if(length(a)==0)next; 
sum=0; for(i=2;i<=length(a);++i){sum+=length(a[i])}; 
print a[1]": "sum; sumTot+=sum} END{print sumTot}'
#+end_src

| header                                                  | length( bp) |
|---------------------------------------------------------+-------------|
| chr1 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    24233538 |
| chr2 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    18891843 |
| chr3 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    20695524 |
| chr4 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    24711646 |
| chr5 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    25650743 |
| chr6 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    22645733 |
| chr7 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    27355740 |
| chr8 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    22550362 |
| chr9 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2   |    23006712 |
| chr10 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    23503040 |
| chr11 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    20118820 |
| chr12 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    24269032 |
| chr13 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    29075116 |
| chr14 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    30274277 |
| chr15 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    20304914 |
| chr16 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    23572818 |
| chr17 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    18691847 |
| chr18 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    34568450 |
| chr19 Vitis vinifera\vert{}PN40024\vert{}assembly12x.2  |    24695667 |
| chrUkn Vitis vinifera\vert{}PN40024\vert{}assembly12x.2 |    27389308 |
| total                                                   |   486205130 |

*** Format =VITVI_PN40024_12x_v0_chroms_URGI= for BLASTn
TODO: change Vvin to VITVI
#+begin_src sh
../../src/format_Vvin-PN40024-12x-chr_blastn.bash
#+end_src

*** Index =VITVI_PN40024_12x_v0_chroms_URGI= for BWA
Launch:
#+begin_src sh
echo "../../src/bwa_index_VITVI_PN40024_12x_v0_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bwa_index_VITVI_PN40024_12x_v0_chroms_URGI -q normal.q
#+end_src

*** Index =VITVI_PN40024_12x_v2_chroms_URGI= for BWA
Launch:
#+begin_src sh
echo "../../src/bwa_index_VITVI_PN40024_12x_v2_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bwa_index_VITVI_PN40024_12x_v2_chroms_URGI -q normal.q
#+end_src

*** Prepare =VITVI_PN40024_12x_v2_chroms_URGI= for SAMtools and Picard
Make an index as well as a SAM header.

Launch:
#+begin_src sh
echo "../../src/samtools-picard_prep_VITVI_PN40024_12x_v2_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N samtools-picard_prep_VITVI_PN40024_12x_v2_chroms_URGI -q normal.q
#+end_src

*** Index =VITVI_PN40024_12x_v0_chroms_URGI= for Bowtie2
Launch:
#+begin_src sh
echo "../../src/bowtie2_index_VITVI_PN40024_12x_v0_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bowtie2_build_VITVI_PN40024_12x_v0_chroms_URGI -q normal.q
#+end_src

*** Index =VITVI_PN40024_12x_v2_chroms_URGI= for Bowtie2
Launch:
#+begin_src sh
echo "../../src/bowtie2_index_VITVI_PN40024_12x_v2_chroms_URGI.bash" \
  | qsub -cwd -j y -V -N bowtie2_build_VITVI_PN40024_12x_v2_chroms_URGI -q normal.q
#+end_src

*** Index =VITVI_PN40024_12x_v2_chroms_URGI= for Bowtie2 compatible with Tassel
Tassel requires numbers as chromosome identifiers.

Launch:
#+begin_src sh
echo "../../src/bowtie2_index_VITVI_PN40024_12x_v2_chroms_URGI_for_Tassel.bash" \
  | qsub -cwd -j y -V -N bowtie2_build_VITVI_PN40024_12x_v2_chroms_URGI_for_Tassel -q normal.q
#+end_src
